# Generated by Django 4.2.5 on 2023-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_asgnodelimits_budget_clusternumnode_cost_nodegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodegroup',
            name='node_fixed_cost',
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='node_cost_per_hr',
            field=models.FloatField(default=0.2016, help_text='https://aws.amazon.com/ec2/pricing/on-demand/ for node'),
        ),
    ]
