# Generated by Django 4.2.5 on 2023-09-11 20:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_nodegroup_node_fixed_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeGroupType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('node_mgnt_fixed_cost', models.FloatField(default=0.145, help_text='https://aws.amazon.com/ec2/pricing/on-demand/ for monitor and ilb')),
                ('per_node_cost_per_hr', models.FloatField(default=0.2016, help_text='https://aws.amazon.com/ec2/pricing/on-demand/ for node')),
                ('name', models.CharField(default='EC2-c7g.large-t4g.2xlarge', max_length=128)),
                ('description', models.CharField(default='An EC2 instance using c7g.large for the ilb and monitor and t4g.2xlarge for the nodes', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='nodegroup',
            name='node_cost_per_hr',
        ),
        migrations.RemoveField(
            model_name='nodegroup',
            name='node_mgr_fixed_cost',
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_groups', to='users.nodegrouptype'),
        ),
    ]
