# Generated by Django 4.2.5 on 2023-09-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_nodegrouptype_remove_nodegroup_node_cost_per_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegrouptype',
            name='description',
            field=models.CharField(default='Add Description here...', max_length=500),
        ),
    ]
