# Generated by Django 4.2.5 on 2023-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_nodegrouptype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegrouptype',
            name='name',
            field=models.CharField(default='e.g. EC2-c7g.large-t4g.2xlarge', max_length=128),
        ),
        migrations.AlterField(
            model_name='nodegrouptype',
            name='node_mgnt_fixed_cost',
            field=models.FloatField(default=0.0, help_text='https://aws.amazon.com/ec2/pricing/on-demand/ for monitor and ilb'),
        ),
        migrations.AlterField(
            model_name='nodegrouptype',
            name='per_node_cost_per_hr',
            field=models.FloatField(default=0.0, help_text='https://aws.amazon.com/ec2/pricing/on-demand/ for node'),
        ),
    ]
