# Generated by Django 4.2.5 on 2023-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_nodegrouptype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaccount',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
