# Generated by Django 4.2.5 on 2023-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_orgaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodegrouptype',
            name='definition',
            field=models.CharField(default='EC2-c7g.large-t4g.2xlarge', max_length=128),
        ),
        migrations.AlterField(
            model_name='nodegrouptype',
            name='name',
            field=models.CharField(default='EC2', max_length=128),
        ),
    ]
