# Generated by Django 4.2.5 on 2023-09-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_nodegrouptype_definition_alter_nodegrouptype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodegrouptype',
            name='definition',
        ),
        migrations.AlterField(
            model_name='nodegrouptype',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
