version: '3.9'
services:
  ps-server:
    command: python ps_server.py 
    ports:
      - 50051:50051
    image: icesat2sliderule/sliderule-ps-server-test-stub:${PS_SERVER_DOCKER_TAG}
    container_name: ps-server
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_SESSION_TOKEN=test
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  ps-db:
    image: postgres:13
    container_name: ps-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    container_name: redis
  django-app:
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0   
      - TZ=America/New_York
      - SITE_ID=2
      - PS_WEB_LOG_LEVEL=INFO
      - ACCOUNT_DEFAULT_HTTP_PROTOCOL="http"
      - CSRF_TRUSTED_ORIGINS=http://localhost
      - DJANGO_ALLOWED_HOSTS=.localhost
      - DOCKER_REPO=icesat2sliderule
      - PS_SERVER_DOCKER_TAG=dev
      - PS_WEB_DOCKER_TAG=dev
      - PS_NGINX_DOCKER_TAG=dev
      - POSTGRES_DB=ps_postgres_db
      - POSTGRES_USER=ps_admin
      - POSTGRES_PASSWORD=ps1234
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=ps-db
      - SQL_PORT=5432
      - DOMAIN=localhost
      - PS_BLD_ENVVER=v0.0.0
      - PYTEST_PLUGINS=celery.contrib.pytest
      - GRPC_TIMEOUT_SECS=1800
      - COOLOFF_SECS=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MFA_PLACEHOLDER=123456
    expose:
      - 8000
    image: ${DOCKER_REPO}/sliderule-ps-web:${PS_WEB_DOCKER_TAG}
    container_name: ps-web
    volumes:
      - ./users/migrations:/home/reg_user/ps/users/migrations
      - ./api/migrations:/home/reg_user/ps/api/migrations
      - ${PWD}/api/schema:/home/reg_user/ps/api/schema
      - ~/.aws/:/home/reg_user/.aws/
      - ./htmlcov:/home/reg_user/ps/htmlcov
      - .coveragerc:/home/reg_user/ps/.coveragerc

    depends_on:
      - ps-db
      - redis
      - ps-server
  nginx:
    image: ${DOCKER_REPO}/sliderule-ps-nginx:${PS_NGINX_DOCKER_TAG}
    container_name: ps-nginx
    ports:
      - 80:80
    depends_on:
      - django-app
volumes:
  postgres_data:
networks:
  default:
#    external: true
    name: ps_dev_network
